### ISSUE TITLE
Feature: User can search for recipes using the search bar

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/ajax-project#1]
## ⚙️ Feature

> Users will be able to search for recipes within the search bar

## 📐 Functionality

> Users will be able to type in their desired recipe in the search bar, and a list of 20 recipes will populate on the page

## 🖼️ Wireframes

> 
![image](https://user-images.githubusercontent.com/109618931/192361890-814b02d1-e6fe-4895-bd38-a3cee68e6630.png)
![image](https://user-images.githubusercontent.com/109618931/192361960-84a1cd70-9f58-467d-b77e-622ac8962a2a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create an input form that will allow users to type in and search for recipes
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens
- [x] Create place holder images that will populate as users are searching for recipes
- [x] Listen for 'input' events on the 'search' input to populate recipes
- [x] Apply CSS styling to match wireframe
- [x] Grab recipe data from API
- [x] Ensure each recipe is created and added to the DOM
- [x] Ensure that on page refresh, the search results remain
- [x] Ensure each recipe has its own recipe ID
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [ ] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
