### ISSUE TITLE
Feature: User can save recipes to a favorites list

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/ajax-project#2]
## ⚙️ Feature

> Users will be able to view favorited recipes in a list

## 📐 Functionality

> Users will be able to favorite a recipe by clicking on the heart icon on the recipe. Recipes will be then saved to a favorites list that users can access at the bottom.

## 🖼️ Wireframes

> ![image](https://user-images.githubusercontent.com/109618931/192381435-5389a20b-fcfc-4142-ba7f-12e240c24dad.png)
> ![image](https://user-images.githubusercontent.com/109618931/192381495-79769021-ce55-453c-b0b8-433dd5e752d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Each item that a user favorites will be generated on a 'favorites list'
- [x] Users will be able to access the 'favorites' list at the bottom
- [x] The red heart at the bottom bar will fill 'red' when users are on this view
- [x] Listen for "heart" events/click to change view to favorites list
- [x] Listen for "heart" events/click on the recipe itself to prepend the new object to the favorites view
- [x] Verify favorited entries are saved to local storage along with the rest on page reload
- [x] Ensure that correct images are displaying for each recipe
- [x] Verify that each new favorites are receiving an increment 'favoritesID'

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
