### ISSUE TITLE
Feature: User can add ingredients to shopping list

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/ajax-project#3]
## ⚙️ Feature

> Users will be able to add ingredients to shopping list 'view'

## 📐 Functionality

> Users will be able to quickly add ingredients to shopping list from recipes ingredient list view

## 🖼️ Wireframes

> ![image](https://user-images.githubusercontent.com/109618931/192386374-dfc5f41e-355a-42fb-80bf-d4505a152b27.png)
> ![image](https://user-images.githubusercontent.com/109618931/192386415-7df1a1f2-62fb-4fa6-823a-448ea45b6301.png)
> ![image](https://user-images.githubusercontent.com/109618931/192386482-04fdd750-96d6-4bbe-890c-884cb68355ee.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Users can remove ingredients from shopping list by clicking on the checkbox
- [x] Ingredients will not be removed from the shopping list until the app is refreshed, in case user clicks on checkbox by accident, they can uncheck it
- [x] Listen for 'click' events on the parent element of the ingredient list
- [x] Apply CSS styling
- [x] Listen for 'click' events on the cart so users can change to shopping list view
- [x] Loop through shopping list to append li element to ul element
- [x] Listen for 'submit' event on form
- [x] Create a function to render shopping list items as they are being added
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [ ] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
