### ISSUE TITLE
Feature: User can access recipe ingredients, directions, and nutrition information

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/ajax-project#4]
## ⚙️ Feature

> Users can view recipe ingredients, directions, and nutrition information 

## 📐 Functionality

> Users will be able to view recipe ingredients, directions, and nutrition information after clicking on 'View Recipe' link that will be available for each recipe.

## 🖼️ Wireframes

> ![image](https://user-images.githubusercontent.com/109618931/192388023-8b109503-7e28-4164-8273-0a14a7a51d06.png)
> ![image](https://user-images.githubusercontent.com/109618931/192388094-30f8c8a5-34e3-4f78-88ec-c8e1245cf339.png)
> ![image](https://user-images.githubusercontent.com/109618931/192388161-9b6f4717-7317-4302-8e26-609295deca8c.png)
> ![image](https://user-images.githubusercontent.com/109618931/192388054-7beb097a-9443-4e13-8ae2-dde83a902f04.png) 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] The magnifying glass will be blue when this view is selected
- [x] Listen for 'click' events on the magnifying glass and retain the view the user was previously on
- [x] Create 'a' element that will link the recipe and allow users to click on it and open in a new tab (this will be a link icon)
- [x] Ensure each recipe is paired with the correct image
- [x] Ensure that view remains the same after each page reload
- [x] Ensure that link icon will show 'View Recipe' when hovered
- [x] Apply CSS styling
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [ ] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
