### ISSUE TITLE
Feature: User can remove a recipe from favorites

### ISSUE THREAD

**Issue by lisa-t-nguyen** [lisa-t-nguyen/ajax-project#5]
## ⚙️ Feature

> Users will be able to remove a recipe from their favorites list

## 📐 Functionality

> Users will be able to remove a recipe from their favorites list by clicking on a trash can icon

## 🖼️ Wireframes

> ![image](https://user-images.githubusercontent.com/109618931/192389908-c22be541-6bb9-455a-ac1e-edc583f53077.png)
> ![image](https://user-images.githubusercontent.com/109618931/192389949-f5efcf6e-fcaf-4574-949f-5604a1f84da1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Users will be able to remove an item from their 'favorites' list
- [ ] Add a click target for deleting a favorite on the 'favorites' list on the trash can icon
- [ ] Remove the entry from the data model and the favorites' DOM tree from the page if the user clicks on the trash can icon
- [ ] Show the favorites list if the user clicks on the trash can icon
- [ ] Test all functionality again in a private browsing session
- [ ] Apply CSS styling
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
